name: objects_transfer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  background_locator_2:
  flutter_background_service:
  flutter_isolate:
  location_permissions:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dependency_overrides:
  background_locator_2:
    path: background_locator
  flutter_background_service:
    path: flutter_background_service/packages/flutter_background_service
  flutter_background_service_android:
    path: flutter_background_service/packages/flutter_background_service_android
  flutter_background_service_ios:
    path: flutter_background_service/packages/flutter_background_service_ios
  flutter_background_service_platform_interface:
    path: flutter_background_service/packages/flutter_background_service_platform_interface
  flutter_isolate:
    path: flutter_isolate

flutter:
  uses-material-design: true
