name: objects_transfer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '3.6.2' # Flutter 3.27.4

dependencies:
  flutter:
    sdk: flutter
  background_locator_2:
  battery_info_plugin:
  flutter_background_service:
  flutter_isolate:
  # permission_handler:
  mapbox_gl:
    git:
      url: https://github.com/naviter/flutter_mapbox_gl.git
      ref: ebe3751026cfef18268589256950d6954b0e4faf

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dependency_overrides:
  background_locator_2:
    path: background_locator
  flutter_background_service:
    path: flutter_background_service/packages/flutter_background_service
  flutter_background_service_android:
    path: flutter_background_service/packages/flutter_background_service_android
  flutter_background_service_ios:
    path: flutter_background_service/packages/flutter_background_service_ios
  flutter_background_service_platform_interface:
    path: flutter_background_service/packages/flutter_background_service_platform_interface
  flutter_isolate:
    path: flutter_isolate
  mapbox_gl_platform_interface:
    git:
      url: https://github.com/naviter/flutter_mapbox_gl.git
      ref: ebe3751026cfef18268589256950d6954b0e4faf
      path: mapbox_gl_platform_interface
  mapbox_gl_web:
    git:
      url: https://github.com/naviter/flutter_mapbox_gl.git
      ref: ebe3751026cfef18268589256950d6954b0e4faf
      path: mapbox_gl_web

flutter:
  uses-material-design: true
